version: '3'

services:
  web:
      image: nginx:latest
      ports:
          - "80:80"
  rust-backend:
    build: ./rust-backend
    volumes:
      - ./rust-backend:/usr/src/app
    ports:
      - "3000:3000"

  