version: '3'

services:

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
      - rust-backend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  next-frontend:
    build: ./frontend
    depends_on:
      - rust-backend
    

  rust-backend:
    build: ./rust-backend
    volumes:
      - ./rust-backend:/usr/src/app
    ports:
      - "5000:5000"
