version: '3'

services:

  next-frontend:
    build: ./next-frontend
    container_name: frontend
    depends_on:
      - rust-backend
    ports:
      - "3000:3000"

  rust-backend:
    build: ./rust-backend
    container_name: backend
    depends_on:
      - sqlite
    volumes:
      - ./rust-backend:/usr/src/app
    ports:
      - "5000:5000"

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

networks:
  default:
    name: traefik-setup_default
    external: true
