version: '3'

services:

  next-frontend:
    build: ./next-frontend
    container_name: frontend
    depends_on:
      - rust-backend
    ports:
      - "3000:3000"

  rust-backend:
    build: ./rust-backend
    container_name: backend
    depends_on:
      - redis
    volumes:
      - ./rust-backend:/usr/src/app
    ports:
      - "5000:5000"

  redis:
    image: redis:7.0-alpine
    container_name: redis
    volumes:
      - ./db/:/root/db/
    ports:
      - "6379:6379"

networks:
  default:
    name: traefik-setup_default
    external: true
