name: Rust-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust-backend

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with: 
        ssh_host: ${{secrets.SSH_HOST}}
        ssh_private_key: ${{secrets.SSH_KEY}}
        ssh_user: ${{secrets.SSH_USERNAME}}
        docker_compose_prefix: rust-backend  
        

        


