name: Rust-deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust-backend

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  deploy:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Debug
        run: echo ${{secrets.SSH_HOST}} ${{secrets.SSH_KEY}} ${{secrets.SSH_USERNAME}}

      - name: Deploy Backend Rust
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          #key_path: /root/.ssh/
          #password: ${{secrets.SSH_PASSPHRASE}} 
        


